name: Create development builds

on:
  push:
    branches: ['dev']
    paths:
      - 'dev/client/**'  # Only trigger when files in dev/client folder change

jobs:
  android_development_build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to get full git history for changed-files
      
      - name: Check for changes in client folder
        id: changes
        uses: tj-actions/changed-files@v42
        with:
          files: |
            dev/client/**
          
      - name: Build Android
        if: steps.changes.outputs.any_changed == 'true'
        run: eas build --platform android --profile development
      
      - name: Upload build
        if: steps.changes.outputs.any_changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: android-development-build
          path: .